### ISSUE TITLE
Browserify Failed!: 'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by hackel** [laravel/elixir#280] opened 2015-09-15 02:31 UTC
I'm getting this since upgrading to laravel-elixir 3.2.8 (after upgrading to Laravel 5.1).  Everything worked fine with 2.x.  Running browserify by itself works fine.  Here's my gulpfile (excerpt):
```js
Elixir.config.js.browserify.watchify.enabled = true;
Elixir.config.js.browserify.transformers = [
    {
        name: "browserify-shim"
    },
    {
        name:    "babelify",
        options: {
            "stage":             2,
            "compact":           false,
            "sourceMap":         true,
            "sourceMapRelative": 'public/js',
            "optional":          [
                "spec.protoToAssign",
                "es7.classProperties"
            ],
            "ignore":            "vendor/bower_components",
            "only":              "public/app"
        }
    }
];
Elixir(function (mix) {
    mix.browserify('app.js', 'public/js/quirks.js', 'public/app', {
            // Enable inline source maps
            debug: true,
        });
```
If I remove the "only" option from the babelify transform, everything seems to work fine.  I haven't had much luck searching for a solution.  This is similar, but doesn't seem to apply:  babel/babelify#103  It might also be related to eslint/espree#72

**Comment by JeffreyWay** [comment] 2015-10-13 03:38
Honestly have no idea. I'm going to close this, only because I don't have more information. If you can give me steps to reproduce this, I'll take a look.

**Closed by JeffreyWay** 2015-10-13 03:38 UTC

**Comment by bastiaan89** [comment] 2015-10-15 11:03
I'm having this same issue when trying to use VueStrap with Browserify.
Here's `main.js`:
```javascript
var Vue = require('vue');


new Vue({
    el: '#vue',
    data: {
        message: "hello"
    },
    components: {
        alert: require('vue-strap').alert
    }
});
```
With elixir, I'm just calling `browserify` on `main.js`.

**Comment by Helfull** [comment] 2015-10-17 13:24
i get the same error message if i try to compile vue-strap with my js

```
var alert = require('vue-strap').alert;

module.exports = {

    components: {
        'alert': alert
    }

}
```
gives me
```
[15:19:38] gulp-notify: [Laravel Elixir] Browserify Failed!: 'import' and 'export' may appear only with 'sourceType: module'

G:\Web\computec-it\client-area\node_modules\vue-strap\src\main.js:1
export alert from './Alert.vue'
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
```
here my gulpfile

```
var elixir = require('laravel-elixir');

/*
 |--------------------------------------------------------------------------
 | Elixir Asset Management
 |--------------------------------------------------------------------------
 |
 | Elixir provides a clean, fluent API for defining some basic Gulp tasks
 | for your Laravel application. By default, we are compiling the Sass
 | file for our application, as well as publishing vendor resources.
 |
 */

var npmPath = './node_modules';

var cfg = {
    outputBase: './public/assets',

    libs: {
        js: {
            output: '/js/libs.js',
            files: [
                npmPath + "/bootstrap-sass/assets/javascripts/bootstrap.min.js",
                npmPath + "/sweetalert/dist/sweetalert.min.js"
            ]
        },
        css: {
            output: '/css/libs.css',
            files: [
                npmPath + "/sweetalert/dist/sweetalert.css"
            ]
        }
    }
};

elixir(function(mix) {


    /*===========================================
    =            Compile Application            =
    ===========================================*/
    
    mix.sass('app.scss', './public/assets/css');
    mix.browserify('app.js', './public/assets/js');
    
    /*=====  End of Compile Application  ======*/


    /*=========================================
    =            Libraries compile            =
    =========================================*/
    
    mix.scripts(cfg.libs.js.files, cfg.outputBase + cfg.libs.js.output);
    mix.scripts(cfg.libs.css.files, cfg.outputBase + cfg.libs.css.output);

    mix.version([cfg.outputBase + cfg.libs.js.output, cfg.outputBase + cfg.libs.css.output,'assets/css/app.css', 'assets/js/app.js']);
    
    /*=====  End of Libraries compile  ======*/
    
});

```

also my package.json

```
{
  "private": true,
  "devDependencies": {
    "gulp": "^3.8.8"
  },
  "dependencies": {
    "bootstrap-sass": "^3.0.0",
    "laravel-elixir": "^3.0.0",
    "sweetalert": "^1.1.0",
    "vue-strap": "^0.1.2"
  }
}

```

**Comment by bastiaan89** [comment] 2015-10-17 13:49
@Helfull That's because VueStrap doesn't yet support browserify/vueify. If you take a look at `Alert.vue`, you'll see that there is no `lang="es6"` attribute in the `script` tag.

Currently, you'll have to use webpack to build VueStrap, or use the global version.

**Comment by gbelot2003** [comment] 2015-10-28 07:36
Fresh installation of laravel on homestead, everything else works fine, but, import, export on browserify not working, same error about... 
    [22:00:49] gulp-notify: [Laravel Elixir] Browserify Failed!: Parsing file  /home/ajax/Projects/tracking/resources/assets/js/app/components/about.vue: 'import' and 'export' may appear only with 'sourceType: module' (1:0)
{ [Error: Parsing file /home/ajax/Projects/tracking/resources/assets/js/app/components/about.vue: 'import' and 'export' may appear only with 'sourceType: module' (1:0)]

**Comment by mikebronner** [comment] 2015-11-04 18:50
Getting this issue as well when using nested components. (I registered them globally, and not on the app instance, if that makes a difference.)

**Comment by acacha** [comment] 2016-01-29 09:37
In my case error occurs because I doesn't have .babelrc file

See: http://stackoverflow.com/questions/30386317/babelify-parseerror-on-import-module-from-node-modules

**Comment by oleynikd** [comment] 2016-04-06 20:57
I have the same error when trying to `import` or `export` inside `.vue` component file

**Comment by adamgoose** [comment] 2016-04-28 06:41
I'm experiencing the same issue. :(

Vue 1.0.21
Elixir 4.2.1
Vueify 8.3.9
Elixir Vueify 1.0.3

**Comment by JeffreyWay** [comment] 2016-04-28 12:12
@adamgoose What version of npm and Node are you using?

**Comment by mikebronner** [comment] 2016-04-28 13:36
I also saw this issue with node 5.10.1 and npm 3.something when writing in ES6 style. Changing back to classic JS style worked, but of course didn't solve the issue.

**Comment by JeffreyWay** [comment] 2016-04-28 13:38
I use ES6 stuff all over the place. Adam, show us what your .vue file looks like.

**Comment by adamgoose** [comment] 2016-04-29 05:08
I think I've identified what the error is referring to. I'm trying (from many many many approaches) to compile [Gritcode Components](http://gritcode.github.io/gritcode-components/) into my application. What I've found is that some of the components try to `import './app.scss'` or `import './templates/foo.html'`. See [here](https://github.com/gritcode/gritcode-components/blob/master/src/components/wizard/index.js#L2-L4).

Unfortunately, I've destroyed my .vue file to get the build working for now while I work on my back-end. But it was simply trying to require the aforelinked (that's a new word; learn it, use it, love it) module with `import wizard from 'gritcode-components/src/componenets/wizard'`, as instructed in [their documentation](https://github.com/gritcode/gritcode-components/blob/master/README.md).

**Comment by adamgoose** [comment] 2016-04-29 05:08
NPM v3.8.3
Node v5.10.1

**Comment by tommytompkins** [comment] 2016-07-07 19:51
I'm running into the exact same problem as @adamgoose trying to install Gritcode Components using Laravel 5.2.  I've tried `import` like their documentation says but I get the error:

```
[14:46:25] gulp-notify: [Laravel Elixir] Browserify Failed!: 'import' and 'export' may appear only with 'sourceType: module'

/Users/tommytompkins/eclipse-projects/ucpics/node_modules/gritcode-components/src/components/file-upload/index.js:4
import './file-upload.scss'
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
```

**Comment by hackel** [comment] 2016-07-08 19:59
FYI, with the switch from Browserify to Webpack, this should probably be closed and/or moved over to [JeffreyWay/laravel-elixir-browserify](https://github.com/JeffreyWay/laravel-elixir-browserify).

**Comment by aumbadgah** [comment] 2016-10-05 18:41
Late to the party, but had the same issue. Kept getting `ParseError: 'import' and 'export' may appear only with 'sourceType: module'` when trying to run a project, that worked perfectly in the previous project folder. Copied .babelrc and everything works, again.

**Comment by strathausen** [comment] 2016-12-07 21:24
What does your .babelrc file look like?
