### ISSUE TITLE
Browserify is not watching for changes in non-laravel project

### ISSUE THREAD

**Issue by cvitko** [laravel/elixir#318] opened 2015-10-21 13:18 UTC
I isolated the issue to totally empty project(folder).
Just add package.json
```
{
  "private": true,
  "devDependencies": {
    "gulp": "^3.8.8"
  },
  "dependencies": {
    "laravel-elixir": "^3.0.0"
  }
}
```

and gulpfile.js
```
var elixir = require('laravel-elixir');

elixir(function(mix) {
    mix.browserify('test.js');
});
```

run npm install

create folder structure for assets same as on laravel project:
resources/assets/js
public

and finally create test.js in resources/assets/js  with some code, let's say alert('hello').

run gulp watch

test.js is processed correctly and moved to public/js folder as it should.
But then when I change the test.js file, elixir is not watching for changes. Nothing happens, no error in console.

I tried the same thing with clean install of Laravel and it works correctly.

**Comment by webcodetailor** [comment] 2015-10-25 23:47
I've managed to find out the way to fix this problem. It looks like this happens when watching an NFS volume (on VM, for example). You should set the poll property's value to true at the watchify options object: <code>elixirConfig.js.browserify.watchify.options.poll = true;</code>. 
You can read about this at the Watchify's github page (https://github.com/substack/watchify).

**Comment by cvitko** [comment] 2015-10-26 15:25
I am not watching NFS volume.
But I tried with that setting, but still doesn't work.

**Comment by webcodetailor** [comment] 2015-10-26 19:00
Hm, I've repeated all the steps you've wrote and it all works fine out of the box. I even didn't need to change the poll option (because this time I didn't use VM).

My enviroment 
1) Windows 7x64
2) Node 4.2.1
3) npm 2.14.8
4) gulp 3.9.0
5) laravel-elixir 3.4.2

**Comment by cvitko** [comment] 2015-10-28 08:50
Thanks for trying it. I am on windows 8.1. I updated all tools to latest versions. Still doesn't work.

But I tried on another computer with win 7 and it worked correctly.

I don't know what can be the issue, because it works on my computer with laravel, but not in empty project.

Can anyone else please try this, so we can be sure it is just my computer issue. Thanks.

**Comment by JeffreyWay** [comment] 2015-11-02 03:58
Closing, as nobody else seems to be able to reproduce.

**Closed by JeffreyWay** 2015-11-02 03:58 UTC
Labels: bug

**Comment by jonagoldman** [comment] 2015-11-14 17:20
Having the same problem using Ubuntu 14.
Setting ```elixirConfig.js.browserify.watchify.options.poll = true;``` fixed the issue for me.
Thanks to @webcodetailor!

**Comment by jozan** [comment] 2015-12-06 17:02
I also encountered this issue in non-laravel project using Ubuntu 15.04 desktop. The same `gulpfile.js` works without problems on OS X.

Browserify compiles scripts only once when running `gulp watch` but not when a file has changed. Other tasks (sass, copy) work like expected.

@webcodetailor's suggestion to edit elixir's config indeed fixed the issue for me as well.

```
elixirConfig.js.browserify.watchify.options.poll = true;
```

**Comment by peshkov3** [comment] 2016-06-02 05:52
Thanks to @webcodetailor! It works!

**Comment by guesl** [comment] 2017-02-21 17:30
Thanks to @webcodetailor ! It works. I am working on laravel 5.3. So maybe the command is someting different. I using the command inside the function (mix) after the js instance has been exists:

elixir(function (mix) {
    elixir.config.js.browserify.watchify.options.poll = true;

    mix.browserSync({
        proxy: 'myapp.app'
    });
});
