### ISSUE TITLE
v3.4.1 - vueify doesn't work

### ISSUE THREAD

**Issue by oleynikd** [laravel/elixir#314] opened 2015-10-16 14:44 UTC
Updated to `laravel-elixir` v3.4.1, run `gulp` = broken app. All `.vue` requirements are missing (empty) in `bundle.js`. However browserify does not produce any error.

Rollback to v3.3.4 - everything works fine.

**Comment by JeffreyWay** [comment] 2015-10-19 15:38
Can't reproduce. If you can give me some simple steps to test this out...

**Comment by JeffreyWay** [comment] 2015-10-25 05:39
Okay, closing unless more feedback comes in.

**Closed by JeffreyWay** 2015-10-25 05:39 UTC

**Comment by marcvdm** [comment] 2015-10-27 09:39
I ran into the same problem. My issue was that i manually pushed the vueify transformer onto the elixir config in my gulpfile. But after i updated to the latest elixir it was already in the config so i had 2 of the same transformers. I guess it then broke it.

My fix was just to remove my manual push into the config.

**Comment by oleynikd** [comment] 2015-10-28 20:27
Aha, great tip. I'll try this. Thanks.
