### ISSUE TITLE
'watch-assets' errored after - Gulp

### ISSUE THREAD

**Issue by Rolando-Barbella** [laravel/elixir#181] opened 2015-06-19 09:49 UTC
Hi, I'm running tasks with laravel-elixir and gulp, trying to watch angular js and sass files, the error I'm getting when I run gulp watch is the following:

'watch-assets' errored after 10 ms
[10:19:16] Error: watch ENOSPC
    at errnoException (fs.js:1030:11)
    at FSWatcher.start (fs.js:1062:11)
    at Object.fs.watch (fs.js:1087:11)
    at Gaze._watchDir (/home/rolando/Documents/Projects/Ocupassion/training/subscribe/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:289:30)
    at /home/rolando/Documents/Projects/Ocupassion/training/subscribe/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:358:10
    at iterate (/home/rolando/Documents/Projects/Ocupassion/training/subscribe/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:52:5)
    at Object.forEachSeries (/home/rolando/Documents/Projects/Ocupassion/training/subscribe/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:66:3)
    at Gaze._initWatched (/home/rolando/Documents/Projects/Ocupassion/training/subscribe/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:354:10)
    at Gaze.add (/home/rolando/Documents/Projects/Ocupassion/training/subscribe/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:177:8)
    at new Gaze (/home/rolando/Documents/Projects/Ocupassion/training/subscribe/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:74:10)
Error running task sequence: { task: 'watch-assets',
  message: 'watch-assets catch',
  duration: 0.010231995,
  hrDuration: [ 0, 10231995 ],
  err: { [Error: watch ENOSPC] code: 'ENOSPC', errno: 'ENOSPC', syscall: 'watch' } }

My gulpifile looks like:

```javascript
var elixir = require('laravel-elixir');
var gulp = require('gulp');
require('laravel-elixir-angular');
require('laravel-elixir-sass-compass');

/*
 |--------------------------------------------------------------------------
 | Elixir Asset Management
 |--------------------------------------------------------------------------
 |
 | Elixir provides a clean, fluent API for defining some basic Gulp tasks
 | for your Laravel application. By default, we are compiling the Less
 | file for our application, as well as publishing vendor resources.
 |
 */

var paths = {
  jquery: 'vendor/bower_components/jquery/',
  angular:'vendor/bower_components/angular/',
  bootstrap: 'vendor/bower_components/bootstrap-sass-official/assets/',
}

elixir(function(mix) {
  mix.angular("resources/assets/angular/", "public/js/", "application.js");
  mix.sass('style.scss','public/css/')
    .copy(paths.bootstrap + 'fonts/bootstrap/**', 'public/fonts')
    .copy(paths.bootstrap + 'stylesheets/**', 'public/css')
    .scripts([
      paths.jquery + 'dist/jquery.js',
      paths.bootstrap + 'javascripts/bootstrap.js',
      paths.angular + 'angular.min.js'
    ],'public/js/app.
});
 ```

I will much appreciate your help :)

**Comment by JeffreyWay** [comment] 2015-07-02 17:44
Closing, since can't reproduce.

**Closed by JeffreyWay** 2015-07-02 17:44 UTC

**Comment by 2tunnels** [comment] 2015-07-07 23:51
+1.
Ubuntu 15.04, installed everything (node, npm) from ubuntu repo.

Then installing dependencies getting this message:
npm WARN optional dep failed, continuing fsevents@0.3.6

As I understood fsevents is only for OSX, mby thats why @JeffreyWay can't reproduce.

**Comment by 2tunnels** [comment] 2015-07-08 00:02
Helped me: https://stackoverflow.com/questions/16748737/grunt-watch-error-waiting-fatal-error-watch-enospc

**Comment by Rolando-Barbella** [comment] 2015-07-08 12:43
My issue had to do more with Node and gaze.js that with laravel-elixir, somehow it started working again after deleting the node_modules folder and restarting everything, but every now and then the issue comes back (really weird), try aslo npm update.

**Comment by kayyyy** [comment] 2015-07-30 15:10
I am getting the same error:

```
vagrant@homestead:~/Code/laravoice$ sudo npm install
npm WARN optional dep failed, continuing fsevents@0.3.6
.....
....
```
I get the same error with and without sudo
