### ISSUE TITLE
.styles() does not parse file

### ISSUE THREAD

**Issue by Lednerb** [laravel/elixir#311] opened 2015-10-14 19:42 UTC
Hey @JeffreyWay 

i've installed the [animate.css](https://github.com/daneden/animate.css) package via bower.

The package will be installed under  `bower_components` in a directory called `animate.css`

By linking to the file in the `mix.styles` it would not include the file:

``` javascript
mix.styles([
   './bower_components/animate.css/animate.min.css'
]);
```

I've changed the directory name to `animate` and it worked.
I'm not sure if it's an elixir 'problem' or something else.

I think this problem has not a very high inpact to other users, but maybe it's easy to fix ;)

**Comment by SimonJ** [comment] 2015-11-02 15:16
i had the problem too, so i did this

` .copy('resources/assets/bower/animate.css/animate.min.css', 'public/css/animate.css')`

**Comment by parsnick** [comment] 2015-12-08 19:04
Do you still have this problem?

I'm doing something similar in one of my projects but never came across this issue. Thought I'd take a look, but can't seem to reproduce - I'm getting a `public/css/all.css` file which contains animate.min.css as expected. 

Does this [minimal example](https://github.com/parsnick/elixir-issue-311) work for you, and if so can you break it to illustrate the bug?

**Comment by JeffreyWay** [comment] 2016-04-01 21:04
This must have worked itself out in a commit since this issue was submitted. Just installed a fresh project and can't reproduce. Closing.

**Closed by JeffreyWay** 2016-04-01 21:04 UTC
Labels: bug
